#!/usr/bin/env bash
# Displays process with most open FDs (PID CMD)
lsof -n | grep -E '^[a-zA-Z]' | awk '{print $2}' | sort | uniq -c | sort -nr | head -n 1 | while read count pid; do ps -p "$pid" -o pid=,comm=; done
