#!/usr/bin/env bash
# Displays the PID and name of the process with the most open files

lsof -n | awk '{print $2}' | sort | uniq -c | sort -nr | head -n 1 | while read -r _ pid; do ps -p "$pid" -o pid=,comm=; done
